// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShirtsApp.Api.Data.Database_Config;

#nullable disable

namespace ShirtsApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250209125129_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShirtsApp.Api.Data.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtID"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtID");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            ShirtID = 1,
                            Brand = "Polo",
                            Color = "Black",
                            Size = 30
                        },
                        new
                        {
                            ShirtID = 2,
                            Brand = "Nike",
                            Color = "Gray",
                            Size = 50
                        },
                        new
                        {
                            ShirtID = 3,
                            Brand = "D&G",
                            Color = "Red",
                            Size = 28
                        },
                        new
                        {
                            ShirtID = 4,
                            Brand = "Puma",
                            Color = "Blue",
                            Size = 14
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
