apiVersion: apps/v1
kind: Deployment
metadata:
  name: shirtsseq-app
  namespace: cloud-native-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shirtsseq-app
  template:
    metadata:
      labels:
        app: shirtsseq-app
    spec:
      containers:
      - name: shirtsseq-app
        image: datalust/seq:latest
        ports:
        - containerPort: 5341
        - containerPort: 80
        env:
         - name: ACCEPT_EULA
           value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: shirtsseq
  namespace: cloud-native-dev
spec:
  selector:
    app: shirtsseq-app
  type: NodePort  
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80  
      nodePort: 31534
---
apiVersion: v1
kind: Service
metadata:
  name: shirtsseq-svc
  namespace: cloud-native-dev
spec:
  clusterIP: None # headless service
  selector:
    app: shirtsseq-app
  ports:
    - protocol: TCP
      port: 5341
      targetPort: 5341